language: python
python:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
# Install packages
install:
  - pip install cython numpy scipy matplotlib dateutil pandas patsy statsmodels scikit-learn sympy pytest pytest-cov
  - python setup.py build_ext --inplace --cythonize
script: pytest -s -v pyearth
