package:
  name: pyearth
  version: "0.1"

source:
  git_url: https://github.com/scikit-learn-contrib/py-earth.git

build:
  skip: true  # [py2k]

requirements:
  build:
    - python >=3
    - setuptools
    - cython
    - numpy
    - scikit-learn
  run:
    - python >=3
    - numpy
    - scipy
    - scikit-learn

test:
  requires:
    - numpy
    - scipy
    - scikit-learn
  imports:
    - pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD
