package:
  name: pyearth
  version: "0.1"

source:
  git_url: https://github.com/scikit-learn-contrib/py-earth.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy >=1.20.0
    - scikit-learn >=1.0.0
    - pytest
    - pytest-cov
  run:
    - python
    - numpy >=1.20.0
    - scipy >=1.6.0
    - scikit-learn >=1.0.0

test:
  requires:
    - numpy >=1.20.0
    - scipy >=1.6.0
    - scikit-learn >=1.0.0
    - pytest
    - pytest-cov
  imports:
    - pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD
