package:
  name: pyearth
  version: "0.1"

source:
  git_url: https://github.com/scikit-learn-contrib/py-earth.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scikit-learn
    - nose
    - six
  run:
    - python
    - numpy
    - scipy >=1.10
    - scikit-learn
    - six

test:
  requires:
    - numpy
    - scipy >=1.10
    - scikit-learn
    - nose
  imports:
    - pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD
