name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython numpy scipy scikit-learn nose pytest six
      - name: Build extensions
        run: python setup.py build_ext --inplace --cythonize
      - name: Run tests
        run: pytest -v pyearth/test
