name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython numpy scipy matplotlib scikit-learn nose pandas patsy statsmodels sympy
          pip install .
          pip install black ruff
      - name: Check formatting
        run: black --check .
      - name: Lint
        run: ruff check . --exit-zero
      - name: Build extensions
        run: python setup.py build_ext --inplace --cythonize
      - name: Test
        run: nosetests -s -v pyearth
