name: CI

on:
  pull_request:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .[all_tests]
      - name: Build Cython extensions
        run: |
          python setup.py build_ext --inplace --cythonize
      - name: Run tests
        run: |
          pytest -v
