name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython numpy scipy scikit-learn nose pytest
      - name: Build extensions
        run: python setup.py build_ext --inplace --cythonize
      - name: Run tests
        run: pytest -s -v pyearth
