name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython nose numpy scipy pandas patsy statsmodels scikit-learn sympy
      - name: Build extensions
        run: |
          python setup.py build_ext --inplace
      - name: Run tests
        run: |
          nosetests -s -v pyearth
